services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    networks:
      - app-network
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: randomdb
      POSTGRES_USER: randomuser
      POSTGRES_PASSWORD: randompass
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
    