// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRandom(ctx context.Context, arg CreateRandomParams) error
	DeleteRandom(ctx context.Context, id uuid.UUID) error
	GetAllRandoms(ctx context.Context) ([]Random, error)
	GetRandom(ctx context.Context, id uuid.UUID) (Random, error)
	GetRandomsByUser(ctx context.Context, userID string) ([]Random, error)
	UpdateRandom(ctx context.Context, arg UpdateRandomParams) error
}

var _ Querier = (*Queries)(nil)
